---
- include: install.yml  # install pkgs
- include: services.yml  # running services

- name: setup ovs bridge files
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{item.ovs_br}}
    src: ovsbr.j2
  with_items:
    "{{ovs}}"
  ignore_errors: yes

- name: setup network files
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{item.ovs_nic}}
    src: networks.j2
  with_items:
    "{{ovs}}"
  ignore_errors: yes

- name: restart network and setup ovs bridges - workaround
  shell: "systemctl restart network"
  ignore_errors: yes

- name: stop network - unsolved network issues - workaround
  shell: "systemctl stop network"
  ignore_errors: yes
  
- name: restart NetworkManager
  shell: "systemctl restart NetworkManager"

