---
- name: enable opennebula.repo
  copy: src="opennebula.repo" dest="/etc/yum.repos.d/opennebula.repo" owner=root group=root mode=644
    
- name: Ensure some packages are installed
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"
  when: packages is defined
  tags:
    - install

- name: Make install_gems non interactive
  git: 
    repo: "https://github.com/OpenNebula/one.git"
    dest: /home/vagrant/one
    clone: yes

- name: Run install_gems
  shell: "one/share/install_gems/install_gems --yes"

- name: config sunstone-server
  copy: src="sunstone-server.conf" dest="/etc/one/sunstone-server.conf" owner=root group=root mode=644

- name: configure nfs
  copy: src="exports" dest="/etc/exports" owner=root group=root mode=644
